### ISSUE TITLE
Text file busy

### ISSUE THREAD

**Issue by pape-io** [cider-ci/cider-ci#45] opened 2016-09-01 07:57 UTC
```
-bash: /tmp/ci_working-dir/8861c265-6786-4ef7-a755-7d4394c741af/.cider-ci_private/rspec_5cc64684-85d1-5dfd-b0f7-071902412fb6_wrapper: Text file busy
  Page
```

```
#!/usr/bin/env bash
set -eux
mkdir -p tmp/cache
export PATH=~/.rubies/$RUBY/bin:$PATH
bundle exec rspec $CIDER_CI_TASK_FILE
```

https://ci.local.ch/cider-ci/ui/workspace/trials/8861c265-6786-4ef7-a755-7d4394c741af/scripts/rspec

**Comment by pape-io** [comment] 2016-09-01 07:59
Could be related to the `.ruby-version` we read into ENV vars on parallelized machines?!?!

**Comment by DrTom** [comment] 2016-09-11 19:21
Possibly but I don't think so. We have seen this before. But only very, very rarely. I am closing this since I can't reproduce it.

**Closed by DrTom** 2016-09-11 19:21 UTC

**Comment by pape-io** [comment] 2016-09-12 07:32
We also get this rarely. and only on our high load executors. I assume it's a race condition problem related to the `environment_variables` -> `read_and_replace_with`. 

I will keep an eye on this one.

**Comment by pape-io** [comment] 2016-09-14 11:52
```
export PATH=~/.rubies/$RUBY/bin:$PATH
cider-ci/bin/precompile-assets-with-caching.sh
```
```
-bash: /tmp/ci_working-dir/b4540ef2-f9e2-4a18-ab48-42ded55daa18/.cider-ci_private/precompile-assets_e505fb3b-0abb-5fdc-8c26-bea75874ed05_wrapper: Text file busy
```
https://github.com/local-ch/ama/blob/master/cider-ci/jobs/tests.yml#L53
https://github.com/local-ch/ama/blob/master/cider-ci/bin/precompile-assets-with-caching.sh

**Comment by pape-io** [comment] 2016-09-14 12:13
Actually on our internal HW (load = 20) it's quite reproducible now:
```
-bash: /tmp/ci_working-dir/b4da79dc-97b8-457d-b7e5-54f586c42c20/.cider-ci_private/test_e8b764da-5fe5-51ed-8af8-c5c6eca28d7a_wrapper: Text file busy
```
```
export PATH=~/.rubies/$RUBY/bin:$PATH
xvfb-run --auto-servernum --server-args='-screen 0, 1024x768x24' bundle exec rspec $CIDER_CI_TASK_FILE
```
