### ISSUE TITLE
RabbitMQ down

### ISSUE THREAD

**Issue by pape-io** [cider-ci/cider-ci#21] opened 2015-11-02 14:53 UTC
tried update to Cider-CI_3.8.0-16.beta
```
 ______________________________________________ 
< TASK: server/roles/rabbitmq | rabbitmq_user  >
 ---------------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


failed: [server] => {"cmd": "/usr/sbin/rabbitmqctl -q -n rabbit list_users", "failed": true, "rc": 2}
stderr: Error: unable to connect to node 'rabbit@ip-172-31-7-201': nodedown

DIAGNOSTICS
===========

attempted to contact: ['rabbit@ip-172-31-7-201']

rabbit@ip-172-31-7-201:
  * connected to epmd (port 4369) on ip-172-31-7-201
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on ip-172-31-7-201
  * suggestion: start the node

current node details:
- node name: 'rabbitmqctl17518@ip-172-31-7-201'
- home dir: /var/lib/rabbitmq
- cookie hash: SJmxJeWoaj8QMe5Cb1wVAA==


msg: Error:********@ip-172-31-7-201'
- home dir: /var/lib/rabbitmq
- cookie hash: SJmxJeWoaj8QMe5Cb1wVAA==

FATAL: all hosts have already failed -- aborting

```

**Comment by DrTom** [comment] 2015-11-02 19:55
We did not change anything with rabbitmq and we also don't do any custom configuration. 
I can imaging that this is actually a problem with EC2 instances. 
There is some documentation here https://www.rabbitmq.com/ec2.html. Could you have a look at the section "Issues with hostname" and confirm or rule out this particular problem. As far as I understand we could set "localhost" as the hostname in general for Cider-CI (we don't need clustering). 

At any rate, you can try the following quick hack: 

1. on your server: `apt-get purge rabbitmq-server` 
2. We then need to re-install it, set up the vhost and permissions. Try to run the normal playbook with the option `--tag server-rabbitmq`. 

You can also run the full playbook but the above should suffice since the services are restarted via the watchdog. 

There is a real problem If rabbitmq isn't running after this. We need then to tweak the configuration in the deploy project.

**Comment by DrTom** [comment] 2015-11-02 19:59
After further investigation, don't use the `--tag server-rabbitmq`. Just run the normal playbook. 

One question: did you clone your server?

**Comment by pape-io** [comment] 2015-11-03 06:54
I never cloned the server so far. Now I had to, because I had to recover it from a snapshot.

**Comment by pape-io** [comment] 2015-11-03 06:55
I would still have this particular server in frozen state if you went to check it out.

**Comment by DrTom** [comment] 2015-11-03 07:07
I would like to investigate myself if that is possible. Maybe I can find something in the logs. I don't know all the circumstances where a new hostname would be used but I Imagine there can be others than cloning on EC2.

**Comment by DrTom** [comment] 2015-11-03 16:38
The logs showed no idnication of a problem with rabbitmq. 

We performed a deploy on the particular system and could not reproduce the problem. 
The machine seemed to be a bit slow at times. There could be an issue that rabbitmq wasn't up yet and the ansible module doesn't wait long enough. We keep an eye on this. 

Closing this ticke because we could not reproduce the problem.

**Closed by DrTom** 2015-11-03 16:38 UTC
