### ISSUE TITLE
install_firefox-esr -> lbzip2: Cannot exec: No such file or directory

### ISSUE THREAD

**Issue by pape-io** [cider-ci/cider-ci#15] opened 2015-10-12 13:28 UTC
```
 _____________________________________________________ 
/ TASK: install_firefox-esr | shell cd /tmp && tar xf \
\ {{firefox_esr_dl_path}}                             /
 ----------------------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


failed: [executor1] => {"changed": true, "cmd": "cd /tmp && tar xf /tmp/firefox_31.4.0esr.tar.bz2", "delta": "0:00:00.006022", "end": "2015-10-12 13:27:29.894951", "rc": 2, "start": "2015-10-12 13:27:29.888929", "warnings": []}
stderr: tar (child): lbzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by DrTom** [comment] 2015-10-13 07:02
This is bizarr. I cannot reproduce the problem. It works well on our jessie machines.
The specified version of firefox esr can still be downloaded and installed.

Can you try again and see if this problem is persistent? Maybe the download wasn't just working temporarily. 

Then there is something strange you your machine. The default `tar` on jessie depends on `bzip2` and not `lbzip2`. But your machines obviously tried to use `lbzip2`. Our jessie machines don't even have that installed.  What happens if you manually try to unpack the file?

**Comment by DrTom** [comment] 2015-10-21 06:14
bzip will be installed as of 3.8.0-12

**Closed by DrTom** 2015-10-21 06:14 UTC
